
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShapeServiceService", targetNamespace = "http://soap/", wsdlLocation = "http://localhost:8080/shapes?wsdl")
public class ShapeServiceService
    extends Service
{

    private final static URL SHAPESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHAPESERVICESERVICE_EXCEPTION;
    private final static QName SHAPESERVICESERVICE_QNAME = new QName("http://soap/", "ShapeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/shapes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHAPESERVICESERVICE_WSDL_LOCATION = url;
        SHAPESERVICESERVICE_EXCEPTION = e;
    }

    public ShapeServiceService() {
        super(__getWsdlLocation(), SHAPESERVICESERVICE_QNAME);
    }

    public ShapeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHAPESERVICESERVICE_QNAME, features);
    }

    public ShapeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SHAPESERVICESERVICE_QNAME);
    }

    public ShapeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHAPESERVICESERVICE_QNAME, features);
    }

    public ShapeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShapeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShapeService
     */
    @WebEndpoint(name = "ShapeServicePort")
    public ShapeService getShapeServicePort() {
        return super.getPort(new QName("http://soap/", "ShapeServicePort"), ShapeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShapeService
     */
    @WebEndpoint(name = "ShapeServicePort")
    public ShapeService getShapeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap/", "ShapeServicePort"), ShapeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHAPESERVICESERVICE_EXCEPTION!= null) {
            throw SHAPESERVICESERVICE_EXCEPTION;
        }
        return SHAPESERVICESERVICE_WSDL_LOCATION;
    }

}
